import { defineConfig } from 'eslint/config';

export default defineConfig([
  {
    ignores: [
      'node_modules/**',
      '.expo/**',
      'android/**',
      'ios/**',
      'dist/**',
      'build/**',
      'coverage/**',
      'src/**/*.ts',
      'tests/**/*.ts',
      'App.tsx',
    ],
  },
  {
    files: ['**/*.js', '**/*.mjs', '**/*.cjs'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        Audio: 'readonly',
        AudioContext: 'readonly',
        Blob: 'readonly',
        Buffer: 'readonly',
        Date: 'readonly',
        Headers: 'readonly',
        Intl: 'readonly',
        JSON: 'readonly',
        Math: 'readonly',
        NodeFilter: 'readonly',
        Object: 'readonly',
        Response: 'readonly',
        Set: 'readonly',
        String: 'readonly',
        URL: 'readonly',
        btoa: 'readonly',
        document: 'readonly',
        globalThis: 'readonly',
        history: 'readonly',
        localStorage: 'readonly',
        location: 'readonly',
        module: 'readonly',
        navigator: 'readonly',
        setInterval: 'readonly',
        setTimeout: 'readonly',
        window: 'readonly',
        caches: 'readonly',
        clearTimeout: 'readonly',
        console: 'readonly',
        fetch: 'readonly',
        process: 'readonly',
        self: 'readonly',
        Element: 'readonly',
        Event: 'readonly',
        MutationObserver: 'readonly',
        FileReader: 'readonly',
      },
    },
    rules: {
      'no-constant-condition': 'error',
      'no-debugger': 'error',
      'no-duplicate-case': 'error',
      'no-constant-binary-expression': 'error',
      'no-dupe-keys': 'error',
      'no-unexpected-multiline': 'error',
      'no-unreachable': 'error',
      'no-undef': 'error',
      'no-unused-vars': ['warn', { args: 'none', caughtErrors: 'none' }],
    },
  },
]);
